[project]
name = "citycoin"

[contracts.sip-010-trait]
path = "contracts/clarinet/sip-10-ft-standard.clar"
depends_on = []

[contracts.token]
path = "contracts/clarinet/token.clar"
depends_on = ["sip-010-trait"]


[contracts.citycoin]
path = "contracts/clarinet/citycoin.clar"
depends_on = ["token"]

# contracts listed below are used only in test suite
[contracts.malicious]
path = "contracts/clarinet/malicious.clar"
depends_on = ["citycoin"]

[contracts.city_wallet]
path = "contracts/clarinet/city_wallet.clar"
depends_on = ["citycoin"]