[project]
name = "citycoin"

[repl.analysis]
costs_version = 2

# mainnet contract references

[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-auth"
[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-token"
[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-auth"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-token"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-core-v1"
[[project.requirements]]
contract_id = "SP2NS7CNBBN3S9J6M4JJHT7WNBETRSBZ9KPVRENBJ.citycoin-tardis-v2"

# contracts listed below are already deployed
# and added only to ensure clarinet check passes
# a syntax check - no other tests are run

[contracts.miamicoin-auth-mainnet]
path = "contracts/cities/mia/mainnet/miamicoin-auth.clar"
depends_on = []

[contracts.miamicoin-core-v1-mainnet]
path = "contracts/cities/mia/mainnet/miamicoin-core-v1.clar"
depends_on = []

[contracts.miamicoin-token-mainnet]
path = "contracts/cities/mia/mainnet/miamicoin-token.clar"
depends_on = []

[contracts.newyorkcitycoin-auth-mainnet]
path = "contracts/cities/nyc/mainnet/newyorkcitycoin-auth.clar"
depends_on = []

[contracts.newyorkcitycoin-core-v1-mainnet]
path = "contracts/cities/nyc/mainnet/newyorkcitycoin-core-v1.clar"
depends_on = []

[contracts.newyorkcitycoin-token-mainnet]
path = "contracts/cities/nyc/mainnet/newyorkcitycoin-token.clar"
depends_on = []

[contracts.citycoin-tardis-v1-mainnet]
path = "contracts/tardis/mainnet/citycoin-tardis-v1.clar"
depends_on = []
[contracts.citycoin-tardis-v2-mainnet]
path = "contracts/tardis/mainnet/citycoin-tardis-v2.clar"
depends_on = []

[contracts.citycoin-vote-v1-mainnet]
path = "contracts/vote/mainnet/citycoins-vote-v1.clar"
depends_on = []

# all contracts below are used with the testing suite

# MIA V1

[contracts.miamicoin-auth]
path = "contracts/cities/mia/local/miamicoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.miamicoin-core-v1]
path = "contracts/cities/mia/local/miamicoin-core-v1.clar"
depends_on = ["miamicoin-auth", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-core-v1-1]
path = "contracts/cities/mia/local/miamicoin-core-v1.clar"
depends_on = ["miamicoin-auth", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-core-v1-2]
path = "contracts/cities/mia/local/miamicoin-core-v1.clar"
depends_on = ["miamicoin-auth", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-core-v1-patch]
path = "contracts/cities/mia/local/miamicoin-core-v1-patch.clar"
depends_on = ["miamicoin-auth", "miamicoin-core-v1", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-token]
path = "contracts/cities/mia/local/miamicoin-token.clar"
depends_on = ["miamicoin-auth", "citycoin-token-trait", "sip-010-trait-ft-standard"]

# MIA V2

[contracts.miamicoin-auth-v2]
path = "contracts/cities/mia/local/miamicoin-auth-v2.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait", "citycoin-token-v2-trait"]

[contracts.miamicoin-core-v2]
path = "contracts/cities/mia/local/miamicoin-core-v2.clar"
depends_on = ["miamicoin-auth-v2", "miamicoin-token-v2", "citycoin-vrf-v2", "citycoin-core-trait"]

[contracts.miamicoin-core-v2-1]
path = "contracts/cities/mia/local/miamicoin-core-v2.clar"
depends_on = ["miamicoin-auth-v2", "miamicoin-token-v2", "citycoin-vrf-v2", "citycoin-core-trait"]

[contracts.miamicoin-core-v2-2]
path = "contracts/cities/mia/local/miamicoin-core-v2.clar"
depends_on = ["miamicoin-auth-v2", "miamicoin-token-v2", "citycoin-vrf-v2", "citycoin-core-trait"]

[contracts.miamicoin-token-v2]
path = "contracts/cities/mia/local/miamicoin-token-v2.clar"
depends_on = ["miamicoin-token", "miamicoin-auth-v2", "citycoin-token-trait", "citycoin-token-v2-trait", "sip-010-trait-ft-standard"]

## NYC V1

[contracts.newyorkcitycoin-auth]
path = "contracts/cities/nyc/local/newyorkcitycoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.newyorkcitycoin-core-v1]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-core-v1-1]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-core-v1-2]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-core-v1-patch]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1-patch.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-core-v1", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-token]
path = "contracts/cities/nyc/local/newyorkcitycoin-token.clar"
depends_on = ["newyorkcitycoin-auth", "citycoin-token-trait", "sip-010-trait-ft-standard"]

# NYC V2

[contracts.newyorkcitycoin-auth-v2]
path = "contracts/cities/nyc/local/newyorkcitycoin-auth-v2.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait", "citycoin-token-v2-trait"]

[contracts.newyorkcitycoin-core-v2]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v2.clar"
depends_on = ["newyorkcitycoin-auth-v2", "newyorkcitycoin-token-v2", "citycoin-vrf-v2", "citycoin-core-trait", "citycoin-core-trait-v2"]

[contracts.newyorkcitycoin-core-v2-1]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v2.clar"
depends_on = ["newyorkcitycoin-auth-v2", "newyorkcitycoin-token-v2", "citycoin-vrf-v2", "citycoin-core-trait", "citycoin-core-trait-v2"]

[contracts.newyorkcitycoin-core-v2-2]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v2.clar"
depends_on = ["newyorkcitycoin-auth-v2", "newyorkcitycoin-token-v2", "citycoin-vrf-v2", "citycoin-core-trait", "citycoin-core-trait-v2"]

[contracts.newyorkcitycoin-token-v2]
path = "contracts/cities/nyc/local/newyorkcitycoin-token-v2.clar"
depends_on = ["newyorkcitycoin-token", "newyorkcitycoin-auth-v2", "citycoin-token-trait", "citycoin-token-v2-trait", "sip-010-trait-ft-standard"]

# Traits

[contracts.citycoin-core-trait]
path = "contracts/base/local/citycoin-core-trait.clar"
depends_on = []

[contracts.citycoin-core-v2-trait]
path = "contracts/base/local/citycoin-core-v2-trait.clar"
depends_on = []

[contracts.citycoin-token-trait]
path = "contracts/base/local/citycoin-token-trait.clar"
depends_on = []

[contracts.citycoin-token-v2-trait]
path = "contracts/base/local/citycoin-token-v2-trait.clar"
depends_on = []

# Base

[contracts.citycoin-auth]
path = "contracts/base/local/citycoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.citycoin-token]
path = "contracts/base/local/citycoin-token.clar"
depends_on = ["sip-010-trait-ft-standard", "citycoin-auth", "citycoin-token-trait"]

[contracts.citycoin-core-v1]
path = "contracts/base/local/citycoin-core-v1.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.citycoin-core-v2]
path = "contracts/base/local/citycoin-core-v2.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.citycoin-core-v3]
path = "contracts/base/local/citycoin-core-v2.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

# tardis

[contracts.citycoin-tardis-v1]
path = "contracts/tardis/local/citycoin-tardis-v1.clar"
depends_on = ["citycoin-core-v1"]

[contracts.citycoin-tardis-v2]
path = "contracts/tardis/local/citycoin-tardis-v2.clar"
depends_on = ["citycoin-core-v1"]

# utilities

[contracts.sip-010-trait-ft-standard]
path = "contracts/utilities/local/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.test-utils]
path = "contracts/utilities/local/test-utils.clar"
depends_on = ["citycoin-core-v1"]

# vote

[contracts.citycoin-vote-v1]
path = "contracts/vote/local/citycoin-vote-v1.clar"
depends_on = ["citycoin-core-v1"]

# vrf

[contracts.citycoin-vrf]
path = "contracts/vrf/local/citycoin-vrf.clar"
depends_on = []

[contracts.citycoin-vrf-v2]
path = "contracts/vrf/local/citycoin-vrf-v2.clar"
depends_on = ["citycoin-vrf"]
